export const industryConfig = [
  { // Restaurant
    'en-gb': 'Restaurant',
    'en-us': 'Restaurant',
    'fr': 'Restaurant',
    'es': 'Restaurante',
    'it': 'Ristorante',
  },
  { // Butchery
    'en-gb': 'Butchery',
    'en-us': 'Butchery',
    'fr': 'Boucherie',
    'es': 'Carnicería',
    'it': 'Macelleria',
  },
  { // Food production
    'en-gb': 'Food production',
    'en-us': 'Food production',
    'fr': 'Unité de production',
    'es': 'Unidad de producción',
    'it': 'Unità produttiva',
  },
  { // Coffee
    'en-gb': 'Coffee',
    'en-us': 'Coffee',
    'fr': 'Bar',
    'es': 'Bar',
    'it': 'Caffè',
  },
  { // Hotel
    'en-gb': 'Hotel',
    'en-us': 'Hotel',
    'fr': 'Hôtel',
    'es': 'Hotel',
    'it': 'Hotel',
  },
  { // Catering
    'en-gb': 'Catering',
    'en-us': 'Catering',
    'fr': 'Traiteur',
    'es': 'Abastecedor',
    'it': 'Catering',
  },
  { // Food retail
    'en-gb': 'Food retail',
    'en-us': 'Food retail',
    'fr': 'Supermarché',
    'es': 'Supermercado',
    'it': 'Supermercato',
  },
  { // Collectivity
    'en-gb': 'Collectivity',
    'en-us': 'Collectivity',
    'fr': 'Collectivité',
    'es': 'Colectividad',
    'it': 'Comunità',
  },
  { // Bakery
    'en-gb': 'Bakery',
    'en-us': 'Bakery',
    'fr': 'Boulangerie',
    'es': 'Panadería',
    'it': 'Panificio',
  },
]

